version: "3.5" 
services:

  php:
    container_name: ${PHP_CONTAINER_NAME}
    image: ${PHP_IMAGE_NAME}
    build:
      context: ./php
    volumes:
      - "../.:/var/www/html"
    ports:
      - "${PHP_PORT}:80"
    restart: always
    environment:
      XDEBUG_CONFIG: remote_port=${XDEBUG_REMOTE_PORT}
    networks:
      - backend

networks:
  backend:
    name: ${NETWORK_NAME}
    driver: bridge